name: sentinela_app_pos_simulator
description: 'A Spolus Solution for telemetry and monitoring for Vending Machine market. (Simulator)'
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: ^3.8.0

dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.8
    permission_handler: ^12.0.0
    path_provider: ^2.1.5
    device_info_plus: ^11.3.3
    flutter_udid: ^4.0.0
    supabase_flutter: ^2.8.4
    internet_connection_checker_plus: ^2.7.1
    uuid: ^4.5.1
    lottie: ^3.3.1
    bluetooth_classic: ^0.0.3
    encrypt: ^5.0.3
    crypto: ^3.0.6
    wakelock_plus: ^1.2.11
    screen_brightness: ^2.1.2
    get_it: ^8.0.3
    intl: ^0.20.2
    logger: ^2.5.0
    restart_app: ^1.3.2
    firebase_crashlytics: ^5.0.0
    firebase_analytics: ^12.0.0
    firebase_core: ^4.0.0
    flutter_secure_storage: ^9.2.4
    package_info_plus: ^8.3.0
    auto_size_text: ^3.0.0
    battery_plus: ^6.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
    change_app_package_name: ^1.4.0

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/images/
        - assets/lottie/
